### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by fulldecent** [zpoley/json-command#16]
I already have `json` in my `PATH`. 

After running `npm install json`, no files are added to my current path nor does `$ json` run your program. 

Could you please explain how to use your product in this situation.

**Comment by leighmcculloch** [comment]
@fulldecent npm installs binaries into `node_modules/.bin` so if you already have `json` in your path you should be able to instead do `./node_modules/.bin/json` to execute it.

**Comment by zpoley** [comment]
Closing this issue.

@fulldecent please let me know if you're still having issues.

@leighmcculloch thank you for stepping in and helping out!

**Comment by fulldecent** [comment]
Thanks for the explanation
